name: Push image to Docker Hub

on:
  push:
    branches:
      - main
      - push-image

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Get current date
        id: date
        run: echo "NOW=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          tags:
            - ${{ env.IMAGE_NAME }}:latest
            - ${{ env.IMAGE_NAME }}:${{ env.NOW }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
