name: Push image to Docker Hub

on:
  push:
    branches:
      - main
      - push-image


jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}

      - name: Get current date
        id: date
        run: echo "NOW=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - name: Dry Run
        run: echo ${{ github.repository }}:${{ env.NOW }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags:
      #       - ${{ github.repository }}:latest
      #       - ${{ github.repository }}:${{ env.NOW }}
